import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers/theme-provider';

export const metadata: Metadata = {
  title: 'Remote Wave',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning={true}>
      <body className={` antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
